export const USER_REPOSITORY = 'USER_REPOSITORY';
export const FORGET_PASSWORD_REPOSITORY = 'FORGET_PASSWORD_REPOSITORY';

// Interest
export const INTEREST_REPOSITORY = 'INTEREST_REPOSITORY';

// Tribes
export const TRIBE_REPOSITORY = 'TRIBE_REPOSITORY';
export const TRIBE_ACTIVITY_REPOSITORY = 'TRIBE_ACTIVITY_REPOSITORY';
export const TRIBE_POST_REPOSITORY = 'TRIBE_POST_REPOSITORY';
export const TRIBE_POST_ASSET_REPOSITORY = 'TRIBE_POST_ASSET_REPOSITORY';
export const TRIBE_POST_COMMENT_REPOSITORY = 'TRIBE_POST_COMMENT_REPOSITORY';